version: '3.7'

services: 
  nginx: # Load balances the three instances of antaeus
    image: nginx:1.16
    ports: 
    - '80:80'
    volumes:
    - ./proxy_params:/etc/nginx/proxy_params
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
    - antaeus
  antaeus:
    image: pleo/antaeus
    build: .
    environment: 
    - MAX_RETRIES=3
    - GRADLE_OPTS="-Dorg.quartz.properties=antaeus.properties"
    volumes: 
    - pleo-antaeus-build-cache:/root/.gradle
    depends_on: 
    - postgres
  postgres:
    image: postgres:11
    ports: 
    - '5432:5432'
    environment: 
    - POSTGRES_USER=antaeus
    # The password should be properly protected in a production environment
    - POSTGRES_PASSWORD=antaeuspwd
    - POSTGRES_DB=antaeus
    volumes: 
    - ./quartz.sql:/docker-entrypoint-initdb.d/quartz.sql

volumes: 
  pleo-antaeus-build-cache: